include "colors.inc"

define ks 0 // 0.5

material "WhiteSpecular"
{
  color White
  finish
  {
    ambient      0.5
    diffuse      0
    spot         1
    shine        100
    specular     1
  }
}

material "BronzeSpecular"
{
  color Bronze
  finish
  {
    ambient      0.5
    diffuse      0
    spot         1
    shine        100
    specular     1
  }
}

material "AmbientBox"
{
  color Black
  finish
  {
    spot     0
    specular 0
  }
}

material "Material1"
{
  color Red
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material2"
{
  color Green
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material3"
{
  color Blue
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material4"
{
  color Orange
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material5"
{
  color Gray
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material6"
{
  color Coral
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material7"
{
  color Silver
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material8"
{
  color ForestGreen
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material9"
{
  color Aquamarine
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material10"
{
  color Turquoise
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material11"
{
  color Khaki
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material12"
{
  color White
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material13"
{
  color Gold
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material14"
{
  color DarkOliveGreen
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}

material "Material15"
{
  color Brown
  finish
  {
    ambient  1
    diffuse  1
    spot     0.5
    shine    80
    specular ks
  }
}
