include "colors.inc"

material "WhiteSpecular"
{
  ambient  White * 0.5
  diffuse  Black
  spot     White
  shine    100
  specular White
}

material "BronzeSpecular"
{
  ambient  Bronze * 0.5
  diffuse  Black
  spot     Bronze
  shine    100
  specular Bronze
}

material "AmbientBox"
{
  spot     Black
  specular Black
}

material "Material1"
{
  ambient  Red
  diffuse  Red
  spot     Red * 0.5
  shine    80
  specular Black
}

material "Material2"
{
  ambient  Green
  diffuse  Green
  spot     Green * 0.5
  shine    80
  specular Black
}

material "Material3"
{
  ambient  Blue
  diffuse  Blue
  spot     Blue * 0.5
  shine    80
  specular Black
}

material "Material4"
{
  ambient  Orange
  diffuse  Orange
  spot     Orange * 0.5
  shine    80
  specular Black
}

material "Material5"
{
  ambient  Gray
  diffuse  Gray
  spot     Gray * 0.5
  shine    80
  specular Black
}

material "Material6"
{
  ambient  Coral
  diffuse  Coral
  spot     Coral * 0.5
  shine    80
  specular Black
}

material "Material7"
{
  ambient  Silver
  diffuse  Silver
  spot     Silver * 0.5
  shine    80
  specular Black
}

material "Material8"
{
  ambient  ForestGreen
  diffuse  ForestGreen
  spot     ForestGreen * 0.5
  shine    80
  specular Black
}

material "Material9"
{
  ambient  Aquamarine
  diffuse  Aquamarine
  spot     Aquamarine * 0.5
  shine    80
  specular Black
}

material "Material10"
{
  ambient  Turquoise
  diffuse  Turquoise
  spot     Turquoise * 0.5
  shine    80
  specular Black
}

material "Material11"
{
  ambient  Khaki
  diffuse  Khaki
  spot     Khaki * 0.5
  shine    80
  specular Black
}

material "Material12"
{
  ambient  White
  diffuse  White
  spot     White * 0.5
  shine    80
  specular Black
}

material "Material13"
{
  ambient  Gold
  diffuse  Gold
  spot     Gold * 0.5
  shine    80
  specular Black
}

material "Material14"
{
  ambient  DarkOliveGreen
  diffuse  DarkOliveGreen
  spot     DarkOliveGreen * 0.5
  shine    80
  specular Black
}

material "Material15"
{
  ambient  Brown
  diffuse  Brown
  spot     Brown * 0.5
  shine    80
  specular Black
}
